# Generated by Django 5.1.3 on 2024-11-14 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_commentlikemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
