---
name: Checks

on: [push]
jobs:
    test:
      name: Testing
      runs-on: ubuntu-20.04
      steps:
        - name: Login docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

        - name: Checkout
          uses: actions/checkout@v3
        - name: Run tests
          run: docker compose run --rm web sh -c "python manage.py wait_for_db && python manage.py test"